# Generated by Django 4.2.9 on 2024-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('job_name', models.CharField(max_length=60, null=True)),
                ('job_category', models.CharField(max_length=20)),
                ('job_desc', models.CharField(max_length=500)),
                ('job_start', models.DateField(null=True)),
                ('job_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Job Posting',
            },
        ),
    ]
