# Generated by Django 4.2.9 on 2024-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_jobpost_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
