# Generated by Django 4.2.9 on 2024-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_jobapp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='cover_letter',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
