# Generated by Django 4.2.9 on 2024-02-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_jobapp_cover_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapp',
            options={'verbose_name_plural': 'Job Applicants'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job Categories'},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='static/resume'),
        ),
    ]
