# Generated by Django 4.2.9 on 2024-02-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_jobapp_options_alter_jobcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
