# Generated by Django 4.2.9 on 2024-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_jobapp_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='static/resume'),
        ),
    ]
