# Generated by Django 4.2.9 on 2024-01-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20231202_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Product Category'},
        ),
    ]
